model_name_or_path: Qwen/Qwen3-4B-Instruct
adapter_name_or_path: saves/fermata-qwen3-4b/lora/sft
template: qwen3
finetuning_type: lora
trust_remote_code: true

export_dir: outputs/fermata-qwen3-4b-sft-merged
export_size: 2
export_device: cpu
export_legacy_format: false
